services:
  - type: web
    name: industro-plumbers
    runtime: ruby
    plan: free
    buildCommand: bundle install && bundle exec rails assets:precompile && bundle exec rails db:migrate
    startCommand: bundle exec rails server -b 0.0.0.0 -p $PORT
    envVars:
      - key: RAILS_ENV
        value: production
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_LEVEL
        value: info
      - key: DATABASE_URL
        fromDatabase:
          name: industro-plumbers-db
          property: connectionString
      - key: APP_HOST
        value: industro-plumbers.onrender.com
      - key: MAILER_SENDER
        value: noreply@industro-plumbers.onrender.com
      - key: SMTP_ADDRESS
        value: smtp.sendgrid.net
      - key: SMTP_PORT
        value: 587
      - key: SMTP_DOMAIN
        value: industro-plumbers.onrender.com
      - key: SMTP_USERNAME
        value: apikey
      - key: SMTP_PASSWORD
        sync: false

databases:
  - name: industro-plumbers-db
    plan: free
    databaseName: industro_plumbers_production